name: Check version in package.json

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Fetch base branch
        run: git fetch origin master

      - name: Check if version in package.json changed
        id: check_version
        run: |
          git diff origin/master...HEAD package.json > diff.txt
          if grep '"version":' diff.txt > /dev/null; then
            echo "Version updated."
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "Version NOT updated!"
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: Warn if version not updated
        if: steps.check_version.outputs.updated == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "⚠️ 请在 `package.json` 中更新版本号（`version` 字段）以反映本次更改。"
            })
